apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: hello-py-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-py-app
    spec:
      containers:
      - name: hello-py-app
        image: ${OCIR_REGION}/${OCIR_STORAGE_NAMESPACE}/ce-jcc/hello-py-app:${BUILDRUN_VERSION}
        imagePullPolicy: Always
        ports:
#        - name: hello-py-app
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 500Mi
            cpu: 900m
          requests:
            memory: 200Mi
            cpu: 500m
      imagePullSecrets:
        - name: my-ocirsecret